name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          token: ${{ secrets.WORKFLOW }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW }}

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          token: ${{ secrets.WORKFLOW }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW }}

      - name: Instalar Requests (necessário para o script de stats)
        run: pip install requests

      - name: Gerar Minha Nova Stats Customizada
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW }}
        run: python github_stats_custom.py

      - name: Commit e Push de todas as mudanças
        env:
          MY_TOKEN: ${{ secrets.WORKFLOW }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${MY_TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "Update profile badges" || exit 0
          git push
