name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_STATS_TOKEN }} # Adicione estas duas linhas aqui
          persist-credentials: true

      - name: Generate Snake SVG
        uses: Blue/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # ... (passos que você já tem)

      - name: Instalar Requests (necessário para o novo script)
        run: pip install requests

      - name: Gerar Minha Nova Stats Customizada
        env:
          GITHUB_TOKEN: ${{ secrets.MY_STATS_TOKEN }} # Use a Secret que você criou
        run: python github_stats_custom.py

      - name: Commit e Push de todas as mudanças
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .  # O ponto final diz: "salve tudo que mudou, inclusive a nova svg"
          git commit -m "Update profile badges" || exit 0
          git push
